<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/shopping/merchant/datasources/v1/datasourcetypes.proto

namespace RexFeed\Vendor\Google\Shopping\Merchant\DataSources\V1;

use RexFeed\Vendor\Google\Protobuf\Internal\GPBType;
use RexFeed\Vendor\Google\Protobuf\Internal\GPBUtil;
use RexFeed\Vendor\Google\Protobuf\RepeatedField;

/**
 * The product review data source.
 *
 * Generated from protobuf message <code>google.shopping.merchant.datasources.v1.ProductReviewDataSource</code>
 */
class ProductReviewDataSource extends \RexFeed\Vendor\Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \RexFeed\Vendor\GPBMetadata\Google\Shopping\Merchant\Datasources\V1\Datasourcetypes::initOnce();
        parent::__construct($data);
    }

}

