<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/longrunning/operations.proto

namespace RexFeed\Vendor\Google\LongRunning;

use RexFeed\Vendor\Google\Protobuf\Internal\GPBType;
use RexFeed\Vendor\Google\Protobuf\Internal\GPBUtil;
use RexFeed\Vendor\Google\Protobuf\RepeatedField;

/**
 * The request message for
 * [Operations.WaitOperation][google.longrunning.Operations.WaitOperation].
 *
 * Generated from protobuf message <code>google.longrunning.WaitOperationRequest</code>
 */
class WaitOperationRequest extends \RexFeed\Vendor\Google\Protobuf\Internal\Message
{
    /**
     * The name of the operation resource to wait on.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * The maximum duration to wait before timing out. If left blank, the wait
     * will be at most the time permitted by the underlying HTTP/RPC protocol.
     * If RPC context deadline is also specified, the shorter one will be used.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration timeout = 2;</code>
     */
    private $timeout = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           The name of the operation resource to wait on.
     *     @type \RexFeed\Vendor\Google\Protobuf\Duration $timeout
     *           The maximum duration to wait before timing out. If left blank, the wait
     *           will be at most the time permitted by the underlying HTTP/RPC protocol.
     *           If RPC context deadline is also specified, the shorter one will be used.
     * }
     */
    public function __construct($data = NULL) {
        \RexFeed\Vendor\GPBMetadata\Google\Longrunning\Operations::initOnce();
        parent::__construct($data);
    }

    /**
     * The name of the operation resource to wait on.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the operation resource to wait on.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * The maximum duration to wait before timing out. If left blank, the wait
     * will be at most the time permitted by the underlying HTTP/RPC protocol.
     * If RPC context deadline is also specified, the shorter one will be used.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration timeout = 2;</code>
     * @return \RexFeed\Vendor\Google\Protobuf\Duration|null
     */
    public function getTimeout()
    {
        return $this->timeout;
    }

    public function hasTimeout()
    {
        return isset($this->timeout);
    }

    public function clearTimeout()
    {
        unset($this->timeout);
    }

    /**
     * The maximum duration to wait before timing out. If left blank, the wait
     * will be at most the time permitted by the underlying HTTP/RPC protocol.
     * If RPC context deadline is also specified, the shorter one will be used.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration timeout = 2;</code>
     * @param \RexFeed\Vendor\Google\Protobuf\Duration $var
     * @return $this
     */
    public function setTimeout($var)
    {
        GPBUtil::checkMessage($var, \RexFeed\Vendor\Google\Protobuf\Duration::class);
        $this->timeout = $var;

        return $this;
    }

}

