<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitd97624185aa33909cdcc22063f8b28ad
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('RexFeed\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \RexFeed\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInitd97624185aa33909cdcc22063f8b28ad', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \RexFeed\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitd97624185aa33909cdcc22063f8b28ad', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\RexFeed\Vendor\Composer\Autoload\ComposerStaticInitd97624185aa33909cdcc22063f8b28ad::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        $filesToLoad = \RexFeed\Vendor\Composer\Autoload\ComposerStaticInitd97624185aa33909cdcc22063f8b28ad::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

        return $loader;
    }
}
