<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));

return array(
    'RexFeed\\Vendor\\Symfony\\Polyfill\\Php80\\' => array($vendorDir . '/symfony/polyfill-php80'),
    'RexFeed\\Vendor\\Ramsey\\Uuid\\' => array($vendorDir . '/ramsey/uuid/src'),
    'RexFeed\\Vendor\\Ramsey\\Collection\\' => array($vendorDir . '/ramsey/collection/src'),
    'RexFeed\\Vendor\\Psr\\Log\\' => array($vendorDir . '/psr/log/src'),
    'RexFeed\\Vendor\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
    'RexFeed\\Vendor\\Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'RexFeed\\Vendor\\Psr\\Cache\\' => array($vendorDir . '/psr/cache/src'),
    'RexFeed\\Vendor\\GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'RexFeed\\Vendor\\GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'RexFeed\\Vendor\\GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'RexFeed\\Vendor\\Grpc\\Gcp\\' => array($vendorDir . '/google/grpc-gcp/src'),
    'RexFeed\\Vendor\\Grpc\\' => array($vendorDir . '/grpc/grpc/src/lib'),
    'RexFeed\\Vendor\\Google\\Type\\' => array($vendorDir . '/google/common-protos/src/Type'),
    'RexFeed\\Vendor\\Google\\Shopping\\Type\\' => array($vendorDir . '/google/shopping-common-protos/src/Type'),
    'RexFeed\\Vendor\\Google\\Shopping\\Merchant\\Reports\\' => array($vendorDir . '/google/shopping-merchant-reports/src'),
    'RexFeed\\Vendor\\Google\\Shopping\\Merchant\\DataSources\\' => array($vendorDir . '/google/shopping-merchant-datasources/src'),
    'RexFeed\\Vendor\\Google\\Rpc\\' => array($vendorDir . '/google/common-protos/src/Rpc'),
    'RexFeed\\Vendor\\Google\\Protobuf\\' => array($vendorDir . '/google/protobuf/src/Google/Protobuf'),
    'RexFeed\\Vendor\\Google\\LongRunning\\' => array($vendorDir . '/google/longrunning/src/LongRunning'),
    'RexFeed\\Vendor\\Google\\Iam\\' => array($vendorDir . '/google/common-protos/src/Iam'),
    'RexFeed\\Vendor\\Google\\Cloud\\' => array($vendorDir . '/google/common-protos/src/Cloud'),
    'RexFeed\\Vendor\\Google\\Auth\\' => array($vendorDir . '/google/auth/src'),
    'RexFeed\\Vendor\\Google\\Api\\' => array($vendorDir . '/google/common-protos/src/Api'),
    'RexFeed\\Vendor\\Google\\ApiCore\\LongRunning\\' => array($vendorDir . '/google/longrunning/src/ApiCore/LongRunning'),
    'RexFeed\\Vendor\\Google\\ApiCore\\' => array($vendorDir . '/google/gax/src'),
    'RexFeed\\Vendor\\GPBMetadata\\Google\\Type\\' => array($vendorDir . '/google/common-protos/metadata/Type'),
    'RexFeed\\Vendor\\GPBMetadata\\Google\\Shopping\\Type\\' => array($vendorDir . '/google/shopping-common-protos/metadata/Type'),
    'RexFeed\\Vendor\\GPBMetadata\\Google\\Shopping\\Merchant\\Reports\\' => array($vendorDir . '/google/shopping-merchant-reports/metadata'),
    'RexFeed\\Vendor\\GPBMetadata\\Google\\Shopping\\Merchant\\Datasources\\' => array($vendorDir . '/google/shopping-merchant-datasources/metadata'),
    'RexFeed\\Vendor\\GPBMetadata\\Google\\Rpc\\' => array($vendorDir . '/google/common-protos/metadata/Rpc'),
    'RexFeed\\Vendor\\GPBMetadata\\Google\\Protobuf\\' => array($vendorDir . '/google/protobuf/src/GPBMetadata/Google/Protobuf'),
    'RexFeed\\Vendor\\GPBMetadata\\Google\\Longrunning\\' => array($vendorDir . '/google/longrunning/metadata/Longrunning'),
    'RexFeed\\Vendor\\GPBMetadata\\Google\\Logging\\' => array($vendorDir . '/google/common-protos/metadata/Logging'),
    'RexFeed\\Vendor\\GPBMetadata\\Google\\Iam\\' => array($vendorDir . '/google/common-protos/metadata/Iam'),
    'RexFeed\\Vendor\\GPBMetadata\\Google\\Cloud\\' => array($vendorDir . '/google/common-protos/metadata/Cloud'),
    'RexFeed\\Vendor\\GPBMetadata\\Google\\Api\\' => array($vendorDir . '/google/common-protos/metadata/Api'),
    'RexFeed\\Vendor\\Firebase\\JWT\\' => array($vendorDir . '/firebase/php-jwt/src'),
    'RexFeed\\Vendor\\Brick\\Math\\' => array($vendorDir . '/brick/math/src'),
);
