<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));

return array(
    '78963f698cf542dbcca28c6b304dd996' => $vendorDir . '/symfony/deprecation-contracts/function.php',
    '658287c4b608150bc8da123cbde2a002' => $vendorDir . '/symfony/polyfill-php80/bootstrap.php',
    'b016d3f55bdb33c5515cc41e7bf4f1c0' => $vendorDir . '/ralouphie/getallheaders/src/getallheaders.php',
    'b3ea1319eec88ea6486ae036f4319b11' => $vendorDir . '/guzzlehttp/guzzle/src/functions_include.php',
    '80af8457a40272b254952ef1d656e79f' => $vendorDir . '/ramsey/uuid/src/functions.php',
);
