<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/shopping/type/types.proto

namespace RexFeed\Vendor\Google\Shopping\Type;

use RexFeed\Vendor\Google\Protobuf\Internal\GPBType;
use RexFeed\Vendor\Google\Protobuf\Internal\GPBUtil;
use RexFeed\Vendor\Google\Protobuf\RepeatedField;

/**
 * [Channel](https://support.google.com/merchants/answer/7361332) of a product.
 * Channel is used to distinguish between online and local products.
 *
 * Generated from protobuf message <code>google.shopping.type.Channel</code>
 */
class Channel extends \RexFeed\Vendor\Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \RexFeed\Vendor\GPBMetadata\Google\Shopping\Type\Types::initOnce();
        parent::__construct($data);
    }

}

