<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/shopping/type/types.proto

namespace RexFeed\Vendor\Google\Shopping\Type;

use RexFeed\Vendor\Google\Protobuf\Internal\GPBType;
use RexFeed\Vendor\Google\Protobuf\Internal\GPBUtil;
use RexFeed\Vendor\Google\Protobuf\RepeatedField;

/**
 * Destinations available for a product.
 * Destinations are used in Merchant Center to allow you to control where the
 * products from your data feed should be displayed.
 *
 * Generated from protobuf message <code>google.shopping.type.Destination</code>
 */
class Destination extends \RexFeed\Vendor\Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \RexFeed\Vendor\GPBMetadata\Google\Shopping\Type\Types::initOnce();
        parent::__construct($data);
    }

}

