<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/rpc/error_details.proto

namespace RexFeed\Vendor\Google\Rpc;

use RexFeed\Vendor\Google\Protobuf\Internal\GPBType;
use RexFeed\Vendor\Google\Protobuf\Internal\GPBUtil;
use RexFeed\Vendor\Google\Protobuf\RepeatedField;

/**
 * Describes what preconditions have failed.
 * For example, if an RPC failed because it required the Terms of Service to be
 * acknowledged, it could list the terms of service violation in the
 * PreconditionFailure message.
 *
 * Generated from protobuf message <code>google.rpc.PreconditionFailure</code>
 */
class PreconditionFailure extends \RexFeed\Vendor\Google\Protobuf\Internal\Message
{
    /**
     * Describes all precondition violations.
     *
     * Generated from protobuf field <code>repeated .google.rpc.PreconditionFailure.Violation violations = 1;</code>
     */
    private $violations;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \RexFeed\Vendor\Google\Rpc\PreconditionFailure\Violation[] $violations
     *           Describes all precondition violations.
     * }
     */
    public function __construct($data = NULL) {
        \RexFeed\Vendor\GPBMetadata\Google\Rpc\ErrorDetails::initOnce();
        parent::__construct($data);
    }

    /**
     * Describes all precondition violations.
     *
     * Generated from protobuf field <code>repeated .google.rpc.PreconditionFailure.Violation violations = 1;</code>
     * @return RepeatedField<\RexFeed\Vendor\Google\Rpc\PreconditionFailure\Violation>
     */
    public function getViolations()
    {
        return $this->violations;
    }

    /**
     * Describes all precondition violations.
     *
     * Generated from protobuf field <code>repeated .google.rpc.PreconditionFailure.Violation violations = 1;</code>
     * @param \RexFeed\Vendor\Google\Rpc\PreconditionFailure\Violation[] $var
     * @return $this
     */
    public function setViolations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \RexFeed\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, \RexFeed\Vendor\Google\Rpc\PreconditionFailure\Violation::class);
        $this->violations = $arr;

        return $this;
    }

}

