<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/auth.proto

namespace RexFeed\Vendor\GPBMetadata\Google\Api;

class Auth
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \RexFeed\Vendor\Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x99\x06\x0A\x15google/api/auth.proto\x12\x0Agoogle.api\"l\x0A\x0EAuthentication\x12-\x0A\x05rules\x18\x03 \x03(\x0B2\x1E.google.api.AuthenticationRule\x12+\x0A\x09providers\x18\x04 \x03(\x0B2\x18.google.api.AuthProvider\"\xA9\x01\x0A\x12AuthenticationRule\x12\x10\x0A\x08selector\x18\x01 \x01(\x09\x12,\x0A\x05oauth\x18\x02 \x01(\x0B2\x1D.google.api.OAuthRequirements\x12 \x0A\x18allow_without_credential\x18\x05 \x01(\x08\x121\x0A\x0Crequirements\x18\x07 \x03(\x0B2\x1B.google.api.AuthRequirement\"^\x0A\x0BJwtLocation\x12\x10\x0A\x06header\x18\x01 \x01(\x09H\x00\x12\x0F\x0A\x05query\x18\x02 \x01(\x09H\x00\x12\x10\x0A\x06cookie\x18\x04 \x01(\x09H\x00\x12\x14\x0A\x0Cvalue_prefix\x18\x03 \x01(\x09B\x04\x0A\x02in\"\x9A\x01\x0A\x0CAuthProvider\x12\x0A\x0A\x02id\x18\x01 \x01(\x09\x12\x0E\x0A\x06issuer\x18\x02 \x01(\x09\x12\x10\x0A\x08jwks_uri\x18\x03 \x01(\x09\x12\x11\x0A\x09audiences\x18\x04 \x01(\x09\x12\x19\x0A\x11authorization_url\x18\x05 \x01(\x09\x12.\x0A\x0Djwt_locations\x18\x06 \x03(\x0B2\x17.google.api.JwtLocation\"-\x0A\x11OAuthRequirements\x12\x18\x0A\x10canonical_scopes\x18\x01 \x01(\x09\"9\x0A\x0FAuthRequirement\x12\x13\x0A\x0Bprovider_id\x18\x01 \x01(\x09\x12\x11\x0A\x09audiences\x18\x02 \x01(\x09Bk\x0A\x0Ecom.google.apiB\x09AuthProtoP\x01ZEgoogle.golang.org/genproto/googleapis/api/serviceconfig;serviceconfig\xA2\x02\x04GAPIb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

