<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/location/locations.proto

namespace RexFeed\Vendor\Google\Cloud\Location;

use RexFeed\Vendor\Google\Protobuf\Internal\GPBType;
use RexFeed\Vendor\Google\Protobuf\Internal\GPBUtil;
use RexFeed\Vendor\Google\Protobuf\RepeatedField;

/**
 * The response message for [Locations.ListLocations][google.cloud.location.Locations.ListLocations].
 *
 * Generated from protobuf message <code>google.cloud.location.ListLocationsResponse</code>
 */
class ListLocationsResponse extends \RexFeed\Vendor\Google\Protobuf\Internal\Message
{
    /**
     * A list of locations that matches the specified filter in the request.
     *
     * Generated from protobuf field <code>repeated .google.cloud.location.Location locations = 1;</code>
     */
    private $locations;
    /**
     * The standard List next-page token.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     */
    protected $next_page_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \RexFeed\Vendor\Google\Cloud\Location\Location[] $locations
     *           A list of locations that matches the specified filter in the request.
     *     @type string $next_page_token
     *           The standard List next-page token.
     * }
     */
    public function __construct($data = NULL) {
        \RexFeed\Vendor\GPBMetadata\Google\Cloud\Location\Locations::initOnce();
        parent::__construct($data);
    }

    /**
     * A list of locations that matches the specified filter in the request.
     *
     * Generated from protobuf field <code>repeated .google.cloud.location.Location locations = 1;</code>
     * @return RepeatedField<\RexFeed\Vendor\Google\Cloud\Location\Location>
     */
    public function getLocations()
    {
        return $this->locations;
    }

    /**
     * A list of locations that matches the specified filter in the request.
     *
     * Generated from protobuf field <code>repeated .google.cloud.location.Location locations = 1;</code>
     * @param \RexFeed\Vendor\Google\Cloud\Location\Location[] $var
     * @return $this
     */
    public function setLocations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \RexFeed\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, \RexFeed\Vendor\Google\Cloud\Location\Location::class);
        $this->locations = $arr;

        return $this;
    }

    /**
     * The standard List next-page token.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @return string
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * The standard List next-page token.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;

        return $this;
    }

}

