<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/backend.proto

namespace RexFeed\Vendor\Google\Api;

use RexFeed\Vendor\Google\Protobuf\Internal\GPBType;
use RexFeed\Vendor\Google\Protobuf\Internal\GPBUtil;
use RexFeed\Vendor\Google\Protobuf\RepeatedField;

/**
 * `Backend` defines the backend configuration for a service.
 *
 * Generated from protobuf message <code>google.api.Backend</code>
 */
class Backend extends \RexFeed\Vendor\Google\Protobuf\Internal\Message
{
    /**
     * A list of API backend rules that apply to individual API methods.
     * **NOTE:** All service configuration rules follow "last one wins" order.
     *
     * Generated from protobuf field <code>repeated .google.api.BackendRule rules = 1;</code>
     */
    private $rules;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \RexFeed\Vendor\Google\Api\BackendRule[] $rules
     *           A list of API backend rules that apply to individual API methods.
     *           **NOTE:** All service configuration rules follow "last one wins" order.
     * }
     */
    public function __construct($data = NULL) {
        \RexFeed\Vendor\GPBMetadata\Google\Api\Backend::initOnce();
        parent::__construct($data);
    }

    /**
     * A list of API backend rules that apply to individual API methods.
     * **NOTE:** All service configuration rules follow "last one wins" order.
     *
     * Generated from protobuf field <code>repeated .google.api.BackendRule rules = 1;</code>
     * @return RepeatedField<\RexFeed\Vendor\Google\Api\BackendRule>
     */
    public function getRules()
    {
        return $this->rules;
    }

    /**
     * A list of API backend rules that apply to individual API methods.
     * **NOTE:** All service configuration rules follow "last one wins" order.
     *
     * Generated from protobuf field <code>repeated .google.api.BackendRule rules = 1;</code>
     * @param \RexFeed\Vendor\Google\Api\BackendRule[] $var
     * @return $this
     */
    public function setRules($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \RexFeed\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, \RexFeed\Vendor\Google\Api\BackendRule::class);
        $this->rules = $arr;

        return $this;
    }

}

