<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/client.proto

namespace RexFeed\Vendor\Google\Api;

use RexFeed\Vendor\Google\Protobuf\Internal\GPBType;
use RexFeed\Vendor\Google\Protobuf\Internal\GPBUtil;
use RexFeed\Vendor\Google\Protobuf\RepeatedField;

/**
 * `BatchingConfigProto` defines the batching configuration for an API method.
 *
 * Generated from protobuf message <code>google.api.BatchingConfigProto</code>
 */
class BatchingConfigProto extends \RexFeed\Vendor\Google\Protobuf\Internal\Message
{
    /**
     * The thresholds which trigger a batched request to be sent.
     *
     * Generated from protobuf field <code>.google.api.BatchingSettingsProto thresholds = 1;</code>
     */
    protected $thresholds = null;
    /**
     * The request and response fields used in batching.
     *
     * Generated from protobuf field <code>.google.api.BatchingDescriptorProto batch_descriptor = 2;</code>
     */
    protected $batch_descriptor = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \RexFeed\Vendor\Google\Api\BatchingSettingsProto $thresholds
     *           The thresholds which trigger a batched request to be sent.
     *     @type \RexFeed\Vendor\Google\Api\BatchingDescriptorProto $batch_descriptor
     *           The request and response fields used in batching.
     * }
     */
    public function __construct($data = NULL) {
        \RexFeed\Vendor\GPBMetadata\Google\Api\Client::initOnce();
        parent::__construct($data);
    }

    /**
     * The thresholds which trigger a batched request to be sent.
     *
     * Generated from protobuf field <code>.google.api.BatchingSettingsProto thresholds = 1;</code>
     * @return \RexFeed\Vendor\Google\Api\BatchingSettingsProto|null
     */
    public function getThresholds()
    {
        return $this->thresholds;
    }

    public function hasThresholds()
    {
        return isset($this->thresholds);
    }

    public function clearThresholds()
    {
        unset($this->thresholds);
    }

    /**
     * The thresholds which trigger a batched request to be sent.
     *
     * Generated from protobuf field <code>.google.api.BatchingSettingsProto thresholds = 1;</code>
     * @param \RexFeed\Vendor\Google\Api\BatchingSettingsProto $var
     * @return $this
     */
    public function setThresholds($var)
    {
        GPBUtil::checkMessage($var, \RexFeed\Vendor\Google\Api\BatchingSettingsProto::class);
        $this->thresholds = $var;

        return $this;
    }

    /**
     * The request and response fields used in batching.
     *
     * Generated from protobuf field <code>.google.api.BatchingDescriptorProto batch_descriptor = 2;</code>
     * @return \RexFeed\Vendor\Google\Api\BatchingDescriptorProto|null
     */
    public function getBatchDescriptor()
    {
        return $this->batch_descriptor;
    }

    public function hasBatchDescriptor()
    {
        return isset($this->batch_descriptor);
    }

    public function clearBatchDescriptor()
    {
        unset($this->batch_descriptor);
    }

    /**
     * The request and response fields used in batching.
     *
     * Generated from protobuf field <code>.google.api.BatchingDescriptorProto batch_descriptor = 2;</code>
     * @param \RexFeed\Vendor\Google\Api\BatchingDescriptorProto $var
     * @return $this
     */
    public function setBatchDescriptor($var)
    {
        GPBUtil::checkMessage($var, \RexFeed\Vendor\Google\Api\BatchingDescriptorProto::class);
        $this->batch_descriptor = $var;

        return $this;
    }

}

