<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/source_info.proto

namespace RexFeed\Vendor\Google\Api;

use RexFeed\Vendor\Google\Protobuf\Internal\GPBType;
use RexFeed\Vendor\Google\Protobuf\Internal\GPBUtil;
use RexFeed\Vendor\Google\Protobuf\RepeatedField;

/**
 * Source information used to create a Service Config
 *
 * Generated from protobuf message <code>google.api.SourceInfo</code>
 */
class SourceInfo extends \RexFeed\Vendor\Google\Protobuf\Internal\Message
{
    /**
     * All files used during config generation.
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Any source_files = 1;</code>
     */
    private $source_files;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \RexFeed\Vendor\Google\Protobuf\Any[] $source_files
     *           All files used during config generation.
     * }
     */
    public function __construct($data = NULL) {
        \RexFeed\Vendor\GPBMetadata\Google\Api\SourceInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * All files used during config generation.
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Any source_files = 1;</code>
     * @return RepeatedField<\RexFeed\Vendor\Google\Protobuf\Any>
     */
    public function getSourceFiles()
    {
        return $this->source_files;
    }

    /**
     * All files used during config generation.
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Any source_files = 1;</code>
     * @param \RexFeed\Vendor\Google\Protobuf\Any[] $var
     * @return $this
     */
    public function setSourceFiles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \RexFeed\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, \RexFeed\Vendor\Google\Protobuf\Any::class);
        $this->source_files = $arr;

        return $this;
    }

}

