<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/shopping/merchant/reports/v1/reports.proto

namespace RexFeed\Vendor\Google\Shopping\Merchant\Reports\V1;

use RexFeed\Vendor\Google\Protobuf\Internal\GPBType;
use RexFeed\Vendor\Google\Protobuf\Internal\GPBUtil;
use RexFeed\Vendor\Google\Protobuf\RepeatedField;

/**
 * Traffic source of impressions in the Competitive visibility report.
 *
 * Generated from protobuf message <code>google.shopping.merchant.reports.v1.TrafficSource</code>
 */
class TrafficSource extends \RexFeed\Vendor\Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \RexFeed\Vendor\GPBMetadata\Google\Shopping\Merchant\Reports\V1\Reports::initOnce();
        parent::__construct($data);
    }

}

